-- MySQL Script generated by MySQL Workbench
-- 12/06/14 00:50:11
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema health_book
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `health_book` ;
USE `health_book` ;

-- -----------------------------------------------------
-- Table `health_book`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_book`.`usuarios` (
  `id_usuario` VARCHAR(13) NOT NULL,
  `UserNames` VARCHAR(15) NOT NULL,
  `UserPassword` VARCHAR(15) NOT NULL,
  `NombreUsuario` VARCHAR(40) NOT NULL,
  `ApellidoUsuario` VARCHAR(40) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `TelefonoUsuario` VARCHAR(10) NOT NULL,
  `CorreoUsuario` VARCHAR(50) NOT NULL,
  `DirrecionUsuario` VARCHAR(100) NOT NULL,
  `EsAdmin` ENUM('0','1') NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `health_book`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_book`.`especialidades` (
  `id_especialidades` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreEspecialidad` VARCHAR(30) NOT NULL,
  `DescripcionEspecialidad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_especialidades`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `health_book`.`doctores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_book`.`doctores` (
  `id_doctor` INT(11) NOT NULL AUTO_INCREMENT,
  `id_especialidad` INT(11) NOT NULL,
  `NombreDoctor` VARCHAR(40) NOT NULL,
  `ApellidoDoctor` VARCHAR(40) NOT NULL,
  `CelularDoctor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_doctor`),
  CONSTRAINT `doctores_ibfk_1`
    FOREIGN KEY (`id_especialidad`)
    REFERENCES `health_book`.`especialidades` (`id_especialidades`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `health_book`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `health_book`.`citas` (
  `id_cita` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` VARCHAR(13) NOT NULL,
  `id_doctor` INT(11) NOT NULL,
  `Fecha_cita` DATE NOT NULL,
  `Hora_cita` VARCHAR(5) NOT NULL,
  `CitaCancelada` ENUM('0','1') NOT NULL,
  PRIMARY KEY (`id_cita`),
  CONSTRAINT `citas_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `health_book`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `citas_ibfk_2`
    FOREIGN KEY (`id_doctor`)
    REFERENCES `health_book`.`doctores` (`id_doctor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;